function state(value,reason){return{state:value,...(reason?{reason}:{})}}
function samePlace(expected,actual){if(!expected||!actual)return false;const eId=String(expected.id??'').trim().toLowerCase(),aId=String(actual.id??'').trim().toLowerCase();if(eId&&aId&&eId===aId)return true;return String(expected.label??'').trim().toLowerCase()===String(actual.label??'').trim().toLowerCase()}
function placeState(set,actual){if(set?.mode==='anywhere')return state('pass');if(!actual)return state('unknown','missing_place');const places=Array.isArray(set?.places)?set.places:[];if(!places.length)return state('unknown','empty_place_set');return state(places.some((place)=>samePlace(place,actual))?'pass':'fail')}
function dateNumber(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const n=Date.parse(`${value}T00:00:00Z`);return Number.isFinite(n)?n:null}
function dayDiff(a,b){const x=dateNumber(a),y=dateNumber(b);return x===null||y===null?null:Math.round((y-x)/86400000)}
function withinDays(actual,target,days=0){const a=dateNumber(actual),t=dateNumber(target);return a!==null&&t!==null&&Math.abs(a-t)<=Number(days||0)*86400000}
function stayState(option,itinerary){const stay=option?.stayLength;if(!stay)return state('pass');const nights=dayDiff(itinerary?.outboundDate,itinerary?.returnDate);if(nights===null)return state('unknown','missing_stay_dates');const min=Number.isFinite(stay.minNights)?stay.minNights:-Infinity,max=Number.isFinite(stay.maxNights)?stay.maxNights:Infinity;return state(nights>=min&&nights<=max?'pass':'fail')}
function dateOptionState(option,itinerary){if(!option)return state('unknown','missing_date_option');if(!itinerary?.outboundDate)return state('unknown','missing_outbound_date');let base;
  if(option.kind==='exact'){if(option.outboundDate&&itinerary.outboundDate!==option.outboundDate)return state('fail');if(option.returnDate){if(!itinerary.returnDate)return state('unknown','missing_return_date');if(itinerary.returnDate!==option.returnDate)return state('fail')}base=state('pass')}
  else if(option.kind==='flexible'){if(!withinDays(itinerary.outboundDate,option.outboundDate,option.outboundFlexDays))return state('fail');if(option.returnDate){if(!itinerary.returnDate)return state('unknown','missing_return_date');if(!withinDays(itinerary.returnDate,option.returnDate,option.returnFlexDays))return state('fail')}base=state('pass')}
  else if(option.kind==='month'){const match=String(itinerary.outboundDate).match(/^(\d{4})-(\d{2})-/);if(!match)return state('unknown','invalid_outbound_date');base=state(Number(match[1])===option.year&&Number(match[2])===option.month?'pass':'fail')}
  else if(option.kind==='range'){const outbound=dateNumber(itinerary.outboundDate),start=dateNumber(option.startDate),end=dateNumber(option.endDate);if([outbound,start,end].some((v)=>v===null))return state('unknown','invalid_range');if(outbound<start||outbound>end)return state('fail');if(itinerary.returnDate){const ret=dateNumber(itinerary.returnDate);if(ret===null)return state('unknown','invalid_return_date');if(ret<start||ret>end)return state('fail')}base=state('pass')}
  else if(option.kind==='anytime')base=state('pass');else return state('unknown','unsupported_date_kind');
  if(base.state!=='pass')return base;return stayState(option,itinerary)}
function dateSetState(set,itinerary){const options=Array.isArray(set?.options)?set.options:[];if(set?.mode==='anytime'&&!options.length)return state('pass');if(!options.length)return state('unknown','empty_date_set');const results=options.map((option)=>dateOptionState(option,itinerary));if(results.some((x)=>x.state==='pass'))return state('pass');if(results.some((x)=>x.state==='unknown'))return state('unknown','date_evidence_incomplete');return state('fail')}
function tripState(intent,itinerary){if(!itinerary?.tripPattern)return state('unknown','missing_trip_pattern');return state(itinerary.tripPattern===intent.tripPattern?'pass':'fail')}
function scenarioState(intent,itinerary){const scenarios=Array.isArray(intent?.scenarios)?intent.scenarios:[];if(!scenarios.length)return null;const results=scenarios.map((scenario)=>{const destination=placeState(scenario.destinationSet||intent.destinationSet,itinerary?.destination),date=dateSetState(scenario.dateSet||intent.dateSet,itinerary);if(destination.state==='pass'&&date.state==='pass')return'pass';if(destination.state==='unknown'||date.state==='unknown')return'unknown';return'fail'});if(results.includes('pass'))return state('pass');if(results.includes('unknown'))return state('unknown','scenario_evidence_incomplete');return state('fail')}
export function evaluateFlightTravelIntent(intent={},itinerary={}){
  const origin=placeState(intent.originSet,itinerary.origin),destination=placeState(intent.destinationSet,itinerary.destination),date=dateSetState(intent.dateSet,itinerary),trip=tripState(intent,itinerary),scenario=scenarioState(intent,itinerary);
  const required=[['originSet',origin],['tripPattern',trip]];
  if(scenario)required.push(['scenario',scenario]);else required.push(['destinationSet',destination],['dateSet',date]);
  const failedRequired=required.filter(([,x])=>x.state==='fail').map(([id])=>id),unknownRequired=required.filter(([,x])=>x.state==='unknown').map(([id])=>id);
  const passed=required.filter(([,x])=>x.state==='pass').length,score=Math.round((passed/required.length)*100);
  return{requiredMatch:failedRequired.length===0&&unknownRequired.length===0,score,origin,destination,date,trip,scenario:scenario||state('pass'),failedRequired,unknownRequired,unsupportedRequired:[],outcomes:required.map(([id,result])=>({condition:{id,fieldId:id,role:'required'},...result}))};
}
