import { parseWatchQuery } from './domain/parseWatch.js';
import { createWatchRecord, loadWatches, saveWatches } from './domain/watchStore.js';
import { loadHistory, appendCheckHistory, previousByCandidate } from './domain/historyStore.js';
import { runWatchCheck } from './connectors/runWatchCheck.js';

const root=document.querySelector('#app');
let watches=loadWatches(localStorage), history=loadHistory(localStorage), resultsByWatch={}, view='today', draft=null, checkingId=null;
const examples=['New Balance 996、24.5cm、グレー、1万円以下','500L以上の冷蔵庫、15万円以下、白かグレー、中古は嫌だけど展示品ならOK','東京からホノルル、直行便、往復10万円以下','軽井沢のホテル、10/26、2万円以下'];
const yen=(v)=>typeof v==='number'?`¥${v.toLocaleString('ja-JP')}`:'—';
const iconFor=(t)=>t==='flight'?'✈':t==='hotel'?'⌂':'◈';
const labelFor=(t)=>t==='flight'?'航空券':t==='hotel'?'ホテル':'買い物';

function chips(w){const c=w.conditions,out=[];if(c.maxPrice)out.push(`${yen(c.maxPrice)}以下`);if(c.size)out.push(c.size);if(c.colors?.length)out.push(c.colors.join('・'));if(c.origin&&c.destination)out.push(`${c.origin} → ${c.destination}`);if(c.directOnly)out.push('直行便');if(c.excludeUsed)out.push('中古除外');if(c.allowDisplay)out.push('展示品OK');return out}
function chipHtml(w){return chips(w).map(x=>`<span>${x}</span>`).join('')}

function render(){root.innerHTML=`<div class="shell"><header class="topbar"><div><div class="brand">Mikke<span>•</span></div><div class="tagline">欲しい条件になったら、見つけておいてくれる。</div></div><button class="bell">◌</button></header><section class="content">${view==='today'?todayView():view==='watch'?watchView():view==='history'?historyView():createView()}</section><nav class="nav"><button class="${view==='today'?'active':''}" data-nav="today"><b>⌂</b><span>Today</span></button><button class="${view==='watch'?'active':''}" data-nav="watch"><b>◫</b><span>Watch</span></button><button class="plus" data-nav="create">＋</button><button class="${view==='history'?'active':''}" data-nav="history"><b>◎</b><span>履歴</span></button><button class="muted" disabled><b>⋯</b><span>設定</span></button></nav></div>`;bindEvents()}

function todayView(){const checked=Object.values(resultsByWatch),matches=checked.flatMap(r=>r.candidates.filter(c=>c.evaluation.requiredMatch));return `<div class="hero"><p class="eyebrow">TODAY</p><h1>今日の動き</h1><p>条件に合うものだけ、変化があった順に。</p></div><div class="stats"><div><b>${matches.length}</b><span>条件一致</span></div><div><b>${watches.length}</b><span>Watch中</span></div><div><b>${checked.length}</b><span>確認済み</span></div></div>${watches.length?`<div class="section-head"><h2>いま見る候補</h2></div><div class="cards">${matches.length?matches.map(productCard).join(''):'<div class="empty-card compact"><h3>まだ条件一致はありません</h3><p>Watchを確認すると候補がまとまります。</p></div>'}</div><div class="section-head"><h2>Watchを確認</h2></div><div class="mini-list">${watches.map(watchRow).join('')}</div>`:`<div class="empty-card"><div class="empty-icon">✦</div><h2>探し回るのを、やめる。</h2><p>欲しい条件を一度登録すれば、Mikkeが変化を見張ります。</p><button class="primary" data-action="open-create">最初のWatchを作る</button></div>`}`}
function watchView(){return `<div class="hero"><p class="eyebrow">WATCH</p><h1>見ておくもの</h1><p>商品でも、航空券でも、ホテルでも。条件で登録します。</p></div><button class="wide-add" data-action="open-create">＋ 新しいWatch</button><div class="watch-list">${watches.length?watches.map(watchCard).join(''):'<p class="subtle">まだWatchがありません。</p>'}</div>`}
function historyView(){const labels={condition_match:'条件一致',new_result:'新着',price_drop:'値下げ',restock:'在庫復活'},items=Object.entries(history).flatMap(([watchId,d])=>(d.events||[]).map(e=>({watchId,...e}))).reverse();return `<div class="hero"><p class="eyebrow">HISTORY</p><h1>変化の履歴</h1><p>意味のあるイベントだけを残します。</p></div><div class="history-list">${items.length?items.map(e=>{const w=watches.find(x=>x.id===e.watchId);return `<article class="history-item"><span class="event-dot"></span><div><small>${labels[e.kind]||e.kind}</small><h3>${w?.title||'Watch'}</h3><p>${e.kind==='price_drop'?`前回より${yen(e.delta)}値下げ`:e.kind==='condition_match'?'設定した必須条件を満たしました':e.kind==='restock'?'在庫が復活しました':'新しい候補を見つけました'}</p></div></article>`}).join(''):'<div class="empty-card compact"><h3>まだ履歴はありません</h3><p>Watchを確認するとここに残ります。</p></div>'}</div>`}
function createView(){if(draft)return confirmView();return `<div class="create-head"><button class="back" data-nav="today">×</button><p class="eyebrow">NEW WATCH</p><h1>何を探しておきますか？</h1><p>欲しい条件をそのまま文章で入力してください。</p></div><form id="watch-form" class="composer"><textarea id="query" maxlength="220" placeholder="例：New Balance 996、24.5cm、グレー、1万円以下"></textarea><div class="examples"><span>入力例</span>${examples.map(x=>`<button type="button" data-example="${x}">${x}</button>`).join('')}</div><button class="primary" type="submit">この内容で条件を作る</button></form>`}
function confirmView(){const cs=chips(draft);return `<div class="create-head"><button class="back" data-action="edit-draft">←</button><p class="eyebrow">CONFIRM</p><h1>この条件で見ておきます</h1><p>曖昧な条件は勝手に追加しません。</p></div><div class="condition-card"><div class="type-icon">${iconFor(draft.type)}</div><div><small>${labelFor(draft.type)}</small><h2>${draft.title}</h2><p>${draft.rawQuery}</p></div></div><div class="condition-groups"><h3>読み取った条件</h3><div class="chips">${cs.length?chipHtml(draft):'<span>詳細条件なし</span>'}</div></div><div class="note">${draft.type==='shopping'?'買い物Watchはデモ候補ですぐ動作確認できます。':`${labelFor(draft.type)}コネクタは次の実装対象です。Watch自体は保存できます。`}</div><button class="primary" data-action="save-watch">この条件をWatchする</button>`}
function watchRow(w){const r=resultsByWatch[w.id],count=r?.candidates.filter(c=>c.evaluation.requiredMatch).length||0;return `<button class="mini-watch" data-check="${w.id}"><span class="mini-icon">${iconFor(w.type)}</span><span><b>${w.title}</b><small>${checkingId===w.id?'確認中…':r?`条件一致 ${count}件`:'タップして確認'}</small></span><i>›</i></button>`}
function watchCard(w){const r=resultsByWatch[w.id];return `<article class="watch-card"><div class="watch-top"><span class="mini-icon">${iconFor(w.type)}</span><div><small>${labelFor(w.type)}</small><h3>${w.title}</h3></div><span class="status">監視中</span></div><p>${w.rawQuery}</p><div class="chips">${chipHtml(w)}</div><button class="check" data-check="${w.id}">${checkingId===w.id?'確認中…':r?'もう一度確認':'今すぐ確認'}</button></article>`}
function productCard(i){const drop=i.previousPrice>i.price?Math.round((1-i.price/i.previousPrice)*100):0;return `<article class="product-card"><div class="product-image"><span>${i.title.includes('冷蔵庫')?'▥':'◒'}</span>${drop?`<b>${drop}% OFF</b>`:''}</div><div><div class="product-head"><div><small>${i.source}</small><h3>${i.title}</h3></div><span class="match">${i.evaluation.score}%</span></div><div class="price-line"><strong>${yen(i.price)}</strong><del>${yen(i.previousPrice)}</del></div><div class="result-badge">✓ 条件に一致</div></div></article>`}

function bindEvents(){document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.nav;if(view!=='create')draft=null;render()}));document.querySelectorAll('[data-action="open-create"]').forEach(b=>b.addEventListener('click',()=>{view='create';draft=null;render()}));document.querySelector('[data-action="edit-draft"]')?.addEventListener('click',()=>{draft=null;render()});document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#query').value=b.dataset.example));document.querySelector('#watch-form')?.addEventListener('submit',e=>{e.preventDefault();const raw=document.querySelector('#query').value.trim();if(!raw)return;draft=parseWatchQuery(raw);render()});document.querySelector('[data-action="save-watch"]')?.addEventListener('click',()=>{const w=createWatchRecord(draft);watches=[w,...watches];saveWatches(localStorage,watches);draft=null;view='watch';render()});document.querySelectorAll('[data-check]').forEach(b=>b.addEventListener('click',async()=>{const w=watches.find(x=>x.id===b.dataset.check);if(!w||checkingId)return;checkingId=w.id;render();const previous=previousByCandidate(history,w.id);resultsByWatch[w.id]=await runWatchCheck(w,previous);history=appendCheckHistory(localStorage,w.id,resultsByWatch[w.id]);checkingId=null;view='today';render()}))}
render();
