import { buildComposerModel, attributePresetPhrases, createComposerModel } from './domain/composerModel.js';

const MODE_KEY='mikke.composer.mode.v1';
let composerMode=localStorage.getItem(MODE_KEY)||'';
let easyType='shopping',easySubject='',easyPhrases=[];
let builderType='shopping',builderSubject='',builderPhrases=[],builderGroup='basic',builderAttribute='';
const labels={shopping:{name:'商品',placeholder:'例：冷蔵庫、スニーカー、ソファ'},flight:{name:'航空券',placeholder:'例：東京からホノルル'},hotel:{name:'ホテル',placeholder:'例：軽井沢'}};

function textarea(form){return form.querySelector('#query')}
function commitRaw(form,raw){const input=textarea(form);if(!input)return;input.value=raw;input.dispatchEvent(new Event('input',{bubbles:true}))}
function buildRaw(type,subject,phrases){const parts=[],clean=subject.trim();if(clean)parts.push(clean);if(type==='flight'&&!/航空券/.test(clean))parts.push('航空券');if(type==='hotel'&&!/ホテル|宿|旅館/.test(clean))parts.push('ホテル');parts.push(...phrases);return parts.filter(Boolean).join('、')}
function hydrateFromRaw(raw){const parts=String(raw||'').split(/[、,]/).map((x)=>x.trim()).filter(Boolean),subject=parts[0]||'',phrases=parts.slice(1).filter((x)=>!['航空券','ホテル'].includes(x));easySubject=subject;builderSubject=subject;easyPhrases=[...phrases];builderPhrases=[...phrases]}
function typeButtons(selected,attr){return Object.entries(labels).map(([key,item])=>`<button type="button" class="type-choice ${selected===key?'active':''}" ${attr}="${key}"><b>${item.name}</b><span>${key==='shopping'?'モノ':key==='flight'?'移動':'宿泊'}</span></button>`).join('')}
function categoryName(model){return model.displayName||{fashion:'ファッション',appliances:'家電',furniture:'家具',food:'食品',used_car:'中古車'}[model.categoryId]||'商品'}
function modelFor(type,subject){return type==='shopping'?buildComposerModel(subject):createComposerModel({type,raw:subject})}
function allEasyEntries(type,model){if(type==='shopping')return[...model.common,...model.category];return[...model.basic,...model.common,...model.detailed]}
function phraseForEntry(entry){return entry.phrases?.[0]||attributePresetPhrases(entry.id)[0]}
function easyOptionsFor(type,subject){const model=modelFor(type,subject),conditionPhrases=allEasyEntries(type,model).map(phraseForEntry).filter(Boolean).slice(0,9),triggerPhrases=(model.triggers||[]).flatMap((item)=>item.phrases?.slice(0,1)||[]).slice(0,3);return[...new Set([...conditionPhrases,...triggerPhrases])].slice(0,12)}

function easyPanel(form){const panel=form.querySelector('.composer-mode-panel');if(!panel)return;const model=modelFor(easyType,easySubject),options=easyOptionsFor(easyType,easySubject);panel.innerHTML=`<div class="guided-flow">
<div class="guided-step"><span>1</span><div><b>何を見つけておく？</b><small>まず種類を選びます</small></div></div><div class="type-choice-grid">${typeButtons(easyType,'data-easy-type')}</div>
<div class="guided-step"><span>2</span><div><b>${labels[easyType].name}を入力</b><small>${easyType==='flight'?'出発地と目的地から始めます':easyType==='hotel'?'行き先から始めます':'名前だけでOK。条件候補を自動で切り替えます'}</small></div></div>
<input class="mode-input" id="easy-subject" value="${escapeHtml(easySubject)}" placeholder="${labels[easyType].placeholder}" />
${easySubject.trim()?`<div class="category-detected"><span>${escapeHtml(categoryName(model))}</span><small>向けの条件を表示中</small></div>`:''}
<div class="guided-step"><span>3</span><div><b>よく使う条件を選ぶ</b><small>必要なものだけ。細かい条件は組み立てで追加できます</small></div></div>
<div class="quick-option-grid">${options.map((item)=>`<button type="button" class="${easyPhrases.includes(item)?'selected':''}" data-easy-option="${escapeHtml(item)}">${escapeHtml(item)}</button>`).join('')||'<span class="mode-empty">入力すると候補が出ます</span>'}</div></div>`}

function groupItems(type,model,group){if(type==='shopping'){if(group==='basic')return model.common;if(group==='common')return model.category;if(group==='advanced'||group==='detailed')return model.advanced;return model.triggers;}if(group==='triggers')return model.triggers||[];return model[group]||[]}
function builderPhraseOptions(model){if(builderGroup==='triggers')return(model.triggers||[]).find((item)=>item.id===builderAttribute)?.phrases||[];const entry=groupItems(builderType,model,builderGroup).find((item)=>item.id===builderAttribute);return entry?.phrases?.length?entry.phrases:attributePresetPhrases(builderAttribute)}
function builderGroupHtml(model,group,title,help){const entries=groupItems(builderType,model,group);if(!entries.length)return'';return`<section class="condition-family ${group==='advanced'?'advanced-family':''}"><div class="condition-family-head"><b>${title}</b><small>${help}</small></div><div class="condition-family-chips">${entries.map((item)=>`<button type="button" class="${builderGroup===group&&builderAttribute===item.id?'active':''}" data-builder-attribute="${escapeHtml(item.id)}" data-builder-group="${group}">${escapeHtml(item.label)}</button>`).join('')}</div></section>`}
function summaryHtml(phrases){return phrases.length?phrases.map((item)=>`<span>${escapeHtml(item)}</span>`).join(''):'<small>下から条件を足していきます</small>'}
function optionButton(item){return`<button type="button" class="${builderPhrases.includes(item)?'selected':''}" data-builder-option="${escapeHtml(item)}">＋ ${escapeHtml(item)}</button>`}

function builderPanel(form){const panel=form.querySelector('.composer-mode-panel');if(!panel)return;const model=modelFor(builderType,builderSubject);let entries=groupItems(builderType,model,builderGroup);if(!entries.length){builderGroup='basic';entries=groupItems(builderType,model,builderGroup)}if(!entries.some((item)=>item.id===builderAttribute))builderAttribute=entries[0]?.id||'';const phraseOptions=builderPhraseOptions(model),domainLabel=categoryName(model);panel.innerHTML=`<div class="builder-flow">
<div class="type-choice-grid compact">${typeButtons(builderType,'data-builder-type')}</div>
<label class="mode-field"><b>探すもの</b><input class="mode-input" id="builder-subject" value="${escapeHtml(builderSubject)}" placeholder="${labels[builderType].placeholder}" /></label>
${builderSubject.trim()?`<div class="category-detected"><span>${escapeHtml(domainLabel)}</span><small>条件テンプレート</small></div>`:''}<div class="builder-summary">${summaryHtml(builderPhrases)}</div>
${builderGroupHtml(model,'basic','基本条件','まずここから')}
${builderGroupHtml(model,'common',builderType==='shopping'?'この商品でよく使う条件':'よく使う条件',`${domainLabel}でよく使います`)}
${builderGroupHtml(model,'detailed','こだわり条件','必要なものだけ追加')}
<section class="condition-family"><div class="condition-family-head"><b>通知タイミング</b><small>いつ知らせるか</small></div><div class="condition-family-chips">${(model.triggers||[]).map((item)=>`<button type="button" class="${builderGroup==='triggers'&&builderAttribute===item.id?'active':''}" data-builder-attribute="${escapeHtml(item.id)}" data-builder-group="triggers">${escapeHtml(item.label)}</button>`).join('')}</div></section>
<details class="advanced-conditions" ${builderGroup==='advanced'?'open':''}><summary>その他の条件</summary>${builderGroupHtml(model,'advanced','高度な条件','必要なときだけ')}</details>
<div class="builder-option-title"><b>${escapeHtml(entries.find((item)=>item.id===builderAttribute)?.label||'')}</b><span>候補</span></div><div class="builder-options">${phraseOptions.map(optionButton).join('')||'<span class="mode-empty">文章入力でも指定できます</span>'}</div></div>`}

function textPanel(form){const panel=form.querySelector('.composer-mode-panel');if(!panel)return;const raw=textarea(form)?.value||'',type=/航空券|フライト|直行便|往復|片道/.test(raw)?'flight':/ホテル|宿|旅館|宿泊/.test(raw)?'hotel':'shopping',model=raw.trim()?modelFor(type,raw):null;panel.innerHTML=`<div class="text-mode-intro"><b>条件を文章でまとめて入力</b><small>例：東京からホノルル、往復、直行便、ANAかJAL、乗り換え1回まで</small>${model?`<span class="text-category">${escapeHtml(categoryName(model))}として条件を整理します</span>`:''}</div>`;const assist=form.querySelector('.assist-label b');if(assist)assist.textContent='入力内容から追加できる条件'}
function applyMode(form){form.classList.remove('composer-awaiting-mode','composer-mode-easy','composer-mode-builder','composer-mode-text');if(!composerMode){form.classList.add('composer-awaiting-mode');const panel=form.querySelector('.composer-mode-panel');if(panel)panel.innerHTML='<p class="mode-prompt">使いやすい入力方法を選んでください。あとから切り替えても入力内容は残ります。</p>';return}form.classList.add(`composer-mode-${composerMode}`);if(composerMode==='easy')easyPanel(form);if(composerMode==='builder')builderPanel(form);if(composerMode==='text')textPanel(form)}

function enhance(form){if(form.dataset.modesEnhanced)return;form.dataset.modesEnhanced='true';const input=textarea(form);if(!input)return;hydrateFromRaw(input.value);const picker=document.createElement('section');picker.className='composer-mode-picker';picker.innerHTML=`<div class="mode-picker-head"><b>Watchの作り方</b><span>いつでも切り替えOK</span></div><div class="mode-cards"><button type="button" data-composer-mode="easy"><span class="mode-icon">①</span><b>かんたん</b><small>質問に答えるだけ</small></button><button type="button" data-composer-mode="builder"><span class="mode-icon">＋</span><b>組み立て</b><small>条件を細かく選ぶ</small></button><button type="button" data-composer-mode="text"><span class="mode-icon">✎</span><b>文章で入力</b><small>まとめて一気に</small></button></div>`;form.insertBefore(picker,input);const panel=document.createElement('div');panel.className='composer-mode-panel';form.insertBefore(panel,input);
form.addEventListener('click',(event)=>{const modeButton=event.target.closest('[data-composer-mode]');if(modeButton){hydrateFromRaw(textarea(form)?.value||'');composerMode=modeButton.dataset.composerMode;localStorage.setItem(MODE_KEY,composerMode);form.querySelectorAll('[data-composer-mode]').forEach((button)=>button.classList.toggle('active',button.dataset.composerMode===composerMode));applyMode(form);return}const easyTypeButton=event.target.closest('[data-easy-type]');if(easyTypeButton){easyType=easyTypeButton.dataset.easyType;easyPhrases=[];commitRaw(form,buildRaw(easyType,easySubject,easyPhrases));easyPanel(form);return}const easyOption=event.target.closest('[data-easy-option]');if(easyOption){const item=easyOption.dataset.easyOption;easyPhrases=easyPhrases.includes(item)?easyPhrases.filter((v)=>v!==item):[...easyPhrases,item];commitRaw(form,buildRaw(easyType,easySubject,easyPhrases));easyPanel(form);return}const builderTypeButton=event.target.closest('[data-builder-type]');if(builderTypeButton){builderType=builderTypeButton.dataset.builderType;builderPhrases=[];builderGroup='basic';builderAttribute='';commitRaw(form,buildRaw(builderType,builderSubject,builderPhrases));builderPanel(form);return}const attr=event.target.closest('[data-builder-attribute]');if(attr){builderGroup=attr.dataset.builderGroup||'basic';builderAttribute=attr.dataset.builderAttribute;builderPanel(form);return}const builderOption=event.target.closest('[data-builder-option]');if(builderOption){const item=builderOption.dataset.builderOption;builderPhrases=builderPhrases.includes(item)?builderPhrases.filter((v)=>v!==item):[...builderPhrases,item];commitRaw(form,buildRaw(builderType,builderSubject,builderPhrases));builderPanel(form)}});
form.addEventListener('input',(event)=>{if(event.target.id==='easy-subject'){easySubject=event.target.value;commitRaw(form,buildRaw(easyType,easySubject,easyPhrases));easyPanel(form)}if(event.target.id==='builder-subject'){builderSubject=event.target.value;commitRaw(form,buildRaw(builderType,builderSubject,builderPhrases));builderPanel(form)}if(event.target.id==='query'&&composerMode==='text')textPanel(form)});form.querySelectorAll('[data-composer-mode]').forEach((button)=>button.classList.toggle('active',button.dataset.composerMode===composerMode));applyMode(form)}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function scan(){const form=document.querySelector('#watch-form');if(form)enhance(form)}
new MutationObserver(scan).observe(document.querySelector('#app'),{childList:true,subtree:true});scan();
