import { buildComposerModel, attributePresetPhrases, createComposerModel, applyFlightTravelIntentEdit } from './domain/composerModel.js';
import { parseWatchQuery } from './domain/parseWatch.js';

const MODE_KEY='mikke.composer.mode.v1';
let composerMode=localStorage.getItem(MODE_KEY)||'';
let easyType='shopping',easySubject='',easyPhrases=[];
let builderType='shopping',builderSubject='',builderPhrases=[],builderGroup='basic',builderAttribute='';
let flightTravelDraft=null,flightDateMode='exact';
const labels={shopping:{name:'商品',placeholder:'例：冷蔵庫、スニーカー、ソファ'},flight:{name:'航空券',placeholder:'例：東京からホノルル'},hotel:{name:'ホテル',placeholder:'例：軽井沢'}};

function textarea(form){return form.querySelector('#query')}
function publishFlightDraft(form){if(form)form._mikkeFlightDraft=flightTravelDraft?structuredClone(flightTravelDraft):null}
function syncFlightDraftFromRaw(raw,form){const text=String(raw||'').trim();if(!text)return;const parsed=parseWatchQuery(text);if(parsed?.domain==='flight'&&parsed?.schemaVersion===4){flightTravelDraft=parsed;publishFlightDraft(form)}}
function commitRaw(form,raw){const input=textarea(form);if(!input)return;input.value=raw;syncFlightDraftFromRaw(raw,form);input.dispatchEvent(new Event('input',{bubbles:true}))}
function buildRaw(type,subject,phrases){const parts=[],clean=subject.trim();if(clean)parts.push(clean);if(type==='flight'&&!/航空券/.test(clean))parts.push('航空券');if(type==='hotel'&&!/ホテル|宿|旅館/.test(clean))parts.push('ホテル');parts.push(...phrases);return parts.filter(Boolean).join('、')}
function hydrateFromRaw(raw,form){const parts=String(raw||'').split(/[、,]/).map((x)=>x.trim()).filter(Boolean),subject=parts[0]||'',phrases=parts.slice(1).filter((x)=>!['航空券','ホテル'].includes(x));easySubject=subject;builderSubject=subject;easyPhrases=[...phrases];builderPhrases=[...phrases];syncFlightDraftFromRaw(raw,form)}
function typeButtons(selected,attr){return Object.entries(labels).map(([key,item])=>`<button type="button" class="type-choice ${selected===key?'active':''}" ${attr}="${key}"><b>${item.name}</b><span>${key==='shopping'?'モノ':key==='flight'?'移動':'宿泊'}</span></button>`).join('')}
function categoryName(model){return model.displayName||{fashion:'ファッション',appliances:'家電',furniture:'家具',food:'食品',used_car:'中古車'}[model.categoryId]||'商品'}
function modelFor(type,subject){return type==='shopping'?buildComposerModel(subject):createComposerModel({type,raw:subject})}
function allEasyEntries(type,model){if(type==='shopping')return[...model.common,...model.category];return[...model.basic,...model.common,...model.detailed]}
function phraseForEntry(entry){return entry.phrases?.[0]||attributePresetPhrases(entry.id)[0]}
function easyOptionsFor(type,subject){const model=modelFor(type,subject),conditionPhrases=allEasyEntries(type,model).map(phraseForEntry).filter(Boolean).slice(0,9),triggerPhrases=(model.triggers||[]).flatMap((item)=>item.phrases?.slice(0,1)||[]).slice(0,3);return[...new Set([...conditionPhrases,...triggerPhrases])].slice(0,12)}
function flightDraft(form){if(!flightTravelDraft)syncFlightDraftFromRaw(textarea(form)?.value||'航空券',form);return flightTravelDraft}
function placeTokens(set,key){if(set.mode==='anywhere')return'<span class="flight-token fixed">どこでも</span>';return(set.places||[]).map((p,index)=>`<span class="flight-token">${escapeHtml(p.label)}<button type="button" aria-label="削除" data-flight-${key}-remove="${index}">×</button></span>`).join('')}
function stayText(option){const s=option?.stayLength;if(!s)return'';return s.minNights===s.maxNights?`${s.minNights}泊`:`${s.minNights}〜${s.maxNights}泊`}
function dateOptionText(option){if(option.kind==='exact')return`${option.outboundDate||'未指定'}${option.returnDate?` → ${option.returnDate}`:''}`;if(option.kind==='flexible')return`${option.outboundDate||''} 前後${option.outboundFlexDays||0}日`;if(option.kind==='month')return`${option.year}年${option.month}月のどこか ${stayText(option)}`.trim();if(option.kind==='range')return`${option.startDate}〜${option.endDate} ${stayText(option)}`.trim();return`いつでも ${stayText(option)}`.trim()}
function dateCards(intent){return(intent.dateSet.options||[]).map((option,index)=>`<div class="flight-date-card"><span>${escapeHtml(dateOptionText(option))}</span><button type="button" aria-label="削除" data-flight-date-remove="${index}">×</button></div>`).join('')||'<small class="flight-empty">候補日を追加できます</small>'}
function filterLabel(filter){const labelsMap={nonstopOnly:'直行',maxStops:'乗継',allowedAirlines:'航空会社',departureTimeRange:'時間帯',checkedBaggageIncluded:'手荷物'};return labelsMap[filter.fieldId]||filter.fieldId}
function flightDateEditor(){if(flightDateMode==='month')return`<div class="flight-date-editor"><input type="month" data-flight-month><input type="number" min="1" max="60" placeholder="最短泊" data-flight-stay-min><input type="number" min="1" max="60" placeholder="最長泊" data-flight-stay-max><button type="button" data-flight-date-add="month">候補を追加</button></div>`;if(flightDateMode==='range')return`<div class="flight-date-editor"><input type="date" data-flight-range-start><input type="date" data-flight-range-end><input type="number" min="1" max="60" placeholder="最短泊" data-flight-stay-min><input type="number" min="1" max="60" placeholder="最長泊" data-flight-stay-max><button type="button" data-flight-date-add="range">候補を追加</button></div>`;if(flightDateMode==='anytime')return`<div class="flight-date-editor"><input type="number" min="1" max="60" placeholder="最短泊" data-flight-stay-min><input type="number" min="1" max="60" placeholder="最長泊" data-flight-stay-max><button type="button" data-flight-date-add="anytime">いつでもを追加</button></div>`;return`<div class="flight-date-editor"><input type="date" data-flight-outbound><input type="date" data-flight-return><button type="button" data-flight-date-add="exact">候補を追加</button></div>`}
function flightIntentPanel(form){const draft=flightDraft(form);if(!draft)return'';const intent=draft.travelIntent;const travellerCount=(intent.travellers.adults||0)+(intent.travellers.children?.length||0)+(intent.travellers.infantsInSeat||0)+(intent.travellers.infantsOnLap||0);const filters=draft.flightFilters||[];return`<div class="flight-intent-panel">
<div class="flight-top-selects"><button type="button" data-flight-trip>${intent.tripPattern==='one_way'?'片道':intent.tripPattern==='multi_city'?'複数都市':'往復'} ▾</button><button type="button" data-flight-cabin>${escapeHtml(intent.cabin.allowed?.[0]||'economy')} ▾</button></div>
<section class="flight-block"><label>出発地</label><div class="flight-token-row">${placeTokens(intent.originSet,'origin')}</div><div class="flight-add-row"><input class="mode-input" placeholder="東京・羽田など" data-flight-place-input="origin"><button type="button" data-flight-place-add="origin">＋追加</button></div></section>
<section class="flight-block"><label>行き先</label><div class="flight-token-row">${placeTokens(intent.destinationSet,'destination')}</div><div class="flight-add-row"><input class="mode-input" placeholder="ホノルル・シドニーなど" data-flight-place-input="destination"><button type="button" data-flight-place-add="destination">＋追加</button></div><button type="button" class="flight-anywhere ${intent.destinationSet.mode==='anywhere'?'active':''}" data-flight-anywhere>行き先はどこでも</button></section>
<section class="flight-block"><label>いつ行く？</label><div class="flight-date-modes"><button type="button" class="${flightDateMode==='exact'?'active':''}" data-flight-date-mode="exact">日付指定</button><button type="button" class="${flightDateMode==='month'?'active':''}" data-flight-date-mode="month">月指定</button><button type="button" class="${flightDateMode==='range'?'active':''}" data-flight-date-mode="range">期間指定</button><button type="button" class="${flightDateMode==='anytime'?'active':''}" data-flight-date-mode="anytime">いつでも</button></div>${flightDateEditor()}<div class="flight-date-options">${dateCards(intent)}</div></section>
<section class="flight-block flight-travellers"><label>人数</label><div><span>大人 ${intent.travellers.adults}</span><span>乳児 ${intent.travellers.infantsOnLap}</span><b>合計 ${travellerCount}人</b></div></section>
<section class="flight-block"><label>よく使う条件</label><div class="flight-primary-filters">${filters.slice(0,5).map((f)=>`<button type="button" class="active">${escapeHtml(filterLabel(f))}</button>`).join('')}<button type="button" data-flight-filter-preset="nonstopOnly">直行</button><button type="button" data-flight-filter-preset="allowedAirlines">航空会社</button><button type="button" data-flight-filter-preset="departureTimeRange">時間帯</button></div><details class="advanced-conditions"><summary>その他の条件</summary><p>乗継・所要時間・手荷物・空港・運賃条件などを追加できます。</p></details></section>
<section class="flight-notification"><label>通知</label><strong>${draft.triggers?.length?'設定した条件になったら知らせる':'条件に合う便が見つかったら'}</strong><small>検索条件とは別に、知らせるタイミングを設定します。</small></section>
</div>`}

function easyPanel(form){const panel=form.querySelector('.composer-mode-panel');if(!panel)return;const model=modelFor(easyType,easySubject),options=easyOptionsFor(easyType,easySubject);if(easyType==='flight'){panel.innerHTML=`<div class="guided-flow"><div class="guided-step"><span>1</span><div><b>何を見つけておく？</b><small>まず種類を選びます</small></div></div><div class="type-choice-grid">${typeButtons(easyType,'data-easy-type')}</div>${flightIntentPanel(form)}</div>`;return}panel.innerHTML=`<div class="guided-flow">
<div class="guided-step"><span>1</span><div><b>何を見つけておく？</b><small>まず種類を選びます</small></div></div><div class="type-choice-grid">${typeButtons(easyType,'data-easy-type')}</div>
<div class="guided-step"><span>2</span><div><b>${labels[easyType].name}を入力</b><small>${easyType==='hotel'?'行き先から始めます':'名前だけでOK。条件候補を自動で切り替えます'}</small></div></div>
<input class="mode-input" id="easy-subject" value="${escapeHtml(easySubject)}" placeholder="${labels[easyType].placeholder}" />
${easySubject.trim()?`<div class="category-detected"><span>${escapeHtml(categoryName(model))}</span><small>向けの条件を表示中</small></div>`:''}
<div class="guided-step"><span>3</span><div><b>よく使う条件を選ぶ</b><small>必要なものだけ。細かい条件は組み立てで追加できます</small></div></div>
<div class="quick-option-grid">${options.map((item)=>`<button type="button" class="${easyPhrases.includes(item)?'selected':''}" data-easy-option="${escapeHtml(item)}">${escapeHtml(item)}</button>`).join('')||'<span class="mode-empty">入力すると候補が出ます</span>'}</div></div>`}

function groupItems(type,model,group){if(type==='shopping'){if(group==='basic')return model.common;if(group==='common')return model.category;if(group==='advanced'||group==='detailed')return model.advanced;return model.triggers;}if(group==='triggers')return model.triggers||[];return model[group]||[]}
function builderPhraseOptions(model){if(builderGroup==='triggers')return(model.triggers||[]).find((item)=>item.id===builderAttribute)?.phrases||[];const entry=groupItems(builderType,model,builderGroup).find((item)=>item.id===builderAttribute);return entry?.phrases?.length?entry.phrases:attributePresetPhrases(builderAttribute)}
function builderGroupHtml(model,group,title,help){const entries=groupItems(builderType,model,group);if(!entries.length)return'';return`<section class="condition-family ${group==='advanced'?'advanced-family':''}"><div class="condition-family-head"><b>${title}</b><small>${help}</small></div><div class="condition-family-chips">${entries.map((item)=>`<button type="button" class="${builderGroup===group&&builderAttribute===item.id?'active':''}" data-builder-attribute="${escapeHtml(item.id)}" data-builder-group="${group}">${escapeHtml(item.label)}</button>`).join('')}</div></section>`}
function summaryHtml(phrases){return phrases.length?phrases.map((item)=>`<span>${escapeHtml(item)}</span>`).join(''):'<small>下から条件を足していきます</small>'}
function optionButton(item){return`<button type="button" class="${builderPhrases.includes(item)?'selected':''}" data-builder-option="${escapeHtml(item)}">＋ ${escapeHtml(item)}</button>`}
function builderPanel(form){const panel=form.querySelector('.composer-mode-panel');if(!panel)return;const model=modelFor(builderType,builderSubject);if(builderType==='flight'){panel.innerHTML=`<div class="builder-flow"><div class="type-choice-grid compact">${typeButtons(builderType,'data-builder-type')}</div>${flightIntentPanel(form)}</div>`;return}let entries=groupItems(builderType,model,builderGroup);if(!entries.length){builderGroup='basic';entries=groupItems(builderType,model,builderGroup)}if(!entries.some((item)=>item.id===builderAttribute))builderAttribute=entries[0]?.id||'';const phraseOptions=builderPhraseOptions(model),domainLabel=categoryName(model);panel.innerHTML=`<div class="builder-flow">
<div class="type-choice-grid compact">${typeButtons(builderType,'data-builder-type')}</div>
<label class="mode-field"><b>探すもの</b><input class="mode-input" id="builder-subject" value="${escapeHtml(builderSubject)}" placeholder="${labels[builderType].placeholder}" /></label>
${builderSubject.trim()?`<div class="category-detected"><span>${escapeHtml(domainLabel)}</span><small>条件テンプレート</small></div>`:''}<div class="builder-summary">${summaryHtml(builderPhrases)}</div>
${builderGroupHtml(model,'basic','基本条件','まずここから')}
${builderGroupHtml(model,'common',builderType==='shopping'?'この商品でよく使う条件':'よく使う条件',`${domainLabel}でよく使います`)}
${builderGroupHtml(model,'detailed','こだわり条件','必要なものだけ追加')}
<section class="condition-family"><div class="condition-family-head"><b>通知タイミング</b><small>いつ知らせるか</small></div><div class="condition-family-chips">${(model.triggers||[]).map((item)=>`<button type="button" class="${builderGroup==='triggers'&&builderAttribute===item.id?'active':''}" data-builder-attribute="${escapeHtml(item.id)}" data-builder-group="triggers">${escapeHtml(item.label)}</button>`).join('')}</div></section>
<details class="advanced-conditions" ${builderGroup==='advanced'?'open':''}><summary>その他の条件</summary>${builderGroupHtml(model,'advanced','高度な条件','必要なときだけ')}</details>
<div class="builder-option-title"><b>${escapeHtml(entries.find((item)=>item.id===builderAttribute)?.label||'')}</b><span>候補</span></div><div class="builder-options">${phraseOptions.map(optionButton).join('')||'<span class="mode-empty">文章入力でも指定できます</span>'}</div></div>`}

function textPanel(form){const panel=form.querySelector('.composer-mode-panel');if(!panel)return;const raw=textarea(form)?.value||'',type=/航空券|フライト|直行便|往復|片道/.test(raw)?'flight':/ホテル|宿|旅館|宿泊/.test(raw)?'hotel':'shopping',model=raw.trim()?modelFor(type,raw):null;panel.innerHTML=`<div class="text-mode-intro"><b>条件を文章でまとめて入力</b><small>例：東京からホノルルかシドニー、2027年2月のどこか、5〜7泊、直行便</small>${model?`<span class="text-category">${escapeHtml(categoryName(model))}として条件を整理します</span>`:''}</div>`;const assist=form.querySelector('.assist-label b');if(assist)assist.textContent='入力内容から追加できる条件'}
function applyMode(form){form.classList.remove('composer-awaiting-mode','composer-mode-easy','composer-mode-builder','composer-mode-text');if(!composerMode){form.classList.add('composer-awaiting-mode');const panel=form.querySelector('.composer-mode-panel');if(panel)panel.innerHTML='<p class="mode-prompt">使いやすい入力方法を選んでください。あとから切り替えても入力内容は残ります。</p>';return}form.classList.add(`composer-mode-${composerMode}`);if(composerMode==='easy')easyPanel(form);if(composerMode==='builder')builderPanel(form);if(composerMode==='text')textPanel(form)}
function rerenderFlight(form){publishFlightDraft(form);if(composerMode==='builder')builderPanel(form);else easyPanel(form)}
function stayFromForm(form){const min=Number(form.querySelector('[data-flight-stay-min]')?.value),max=Number(form.querySelector('[data-flight-stay-max]')?.value);if(!Number.isFinite(min)&&!Number.isFinite(max))return undefined;const a=Number.isFinite(min)&&min>0?min:max,b=Number.isFinite(max)&&max>0?max:a;return{minNights:a,maxNights:b}}
function handleFlightClick(form,event){if(!flightTravelDraft)return false;const dateMode=event.target.closest('[data-flight-date-mode]');if(dateMode){flightDateMode=dateMode.dataset.flightDateMode;rerenderFlight(form);return true}const anywhere=event.target.closest('[data-flight-anywhere]');if(anywhere){flightTravelDraft=applyFlightTravelIntentEdit(flightTravelDraft,{type:'set_place_mode',set:'destination',mode:'anywhere'});rerenderFlight(form);return true}const addPlace=event.target.closest('[data-flight-place-add]');if(addPlace){const set=addPlace.dataset.flightPlaceAdd,input=form.querySelector(`[data-flight-place-input="${set}"]`),label=input?.value.trim();if(label){flightTravelDraft=applyFlightTravelIntentEdit(flightTravelDraft,{type:'add_place',set,place:{kind:'city',id:label,label}});rerenderFlight(form)}return true}const removeDestination=event.target.closest('[data-flight-destination-remove]');if(removeDestination){flightTravelDraft=applyFlightTravelIntentEdit(flightTravelDraft,{type:'remove_place',set:'destination',index:Number(removeDestination.dataset.flightDestinationRemove)});rerenderFlight(form);return true}const removeOrigin=event.target.closest('[data-flight-origin-remove]');if(removeOrigin){flightTravelDraft=applyFlightTravelIntentEdit(flightTravelDraft,{type:'remove_place',set:'origin',index:Number(removeOrigin.dataset.flightOriginRemove)});rerenderFlight(form);return true}const removeDate=event.target.closest('[data-flight-date-remove]');if(removeDate){flightTravelDraft=applyFlightTravelIntentEdit(flightTravelDraft,{type:'remove_date_option',index:Number(removeDate.dataset.flightDateRemove)});rerenderFlight(form);return true}const addDate=event.target.closest('[data-flight-date-add]');if(addDate){const kind=addDate.dataset.flightDateAdd,stay=stayFromForm(form);let option;if(kind==='month'){const month=form.querySelector('[data-flight-month]')?.value;if(month){const[y,m]=month.split('-').map(Number);option={kind:'month',year:y,month:m,...(stay?{stayLength:stay}:{})}}}else if(kind==='range'){const startDate=form.querySelector('[data-flight-range-start]')?.value,endDate=form.querySelector('[data-flight-range-end]')?.value;if(startDate&&endDate)option={kind:'range',startDate,endDate,...(stay?{stayLength:stay}:{})}}else if(kind==='anytime')option={kind:'anytime',...(stay?{stayLength:stay}:{})};else{const outboundDate=form.querySelector('[data-flight-outbound]')?.value,returnDate=form.querySelector('[data-flight-return]')?.value;if(outboundDate)option={kind:'exact',outboundDate,...(returnDate?{returnDate}:{})}}if(option){flightTravelDraft=applyFlightTravelIntentEdit(flightTravelDraft,{type:'add_date_option',option});rerenderFlight(form)}return true}return false}

function enhance(form){if(form.dataset.modesEnhanced)return;form.dataset.modesEnhanced='true';const input=textarea(form);if(!input)return;hydrateFromRaw(input.value,form);const picker=document.createElement('section');picker.className='composer-mode-picker';picker.innerHTML=`<div class="mode-picker-head"><b>Watchの作り方</b><span>いつでも切り替えOK</span></div><div class="mode-cards"><button type="button" data-composer-mode="easy"><span class="mode-icon">①</span><b>かんたん</b><small>質問に答えるだけ</small></button><button type="button" data-composer-mode="builder"><span class="mode-icon">＋</span><b>組み立て</b><small>条件を細かく選ぶ</small></button><button type="button" data-composer-mode="text"><span class="mode-icon">✎</span><b>文章で入力</b><small>まとめて一気に</small></button></div>`;form.insertBefore(picker,input);const panel=document.createElement('div');panel.className='composer-mode-panel';form.insertBefore(panel,input);
form.addEventListener('click',(event)=>{if(handleFlightClick(form,event))return;const modeButton=event.target.closest('[data-composer-mode]');if(modeButton){composerMode=modeButton.dataset.composerMode;localStorage.setItem(MODE_KEY,composerMode);if(flightTravelDraft){flightTravelDraft=applyFlightTravelIntentEdit(flightTravelDraft,{type:'set_input_mode',mode:composerMode});publishFlightDraft(form)}form.querySelectorAll('[data-composer-mode]').forEach((button)=>button.classList.toggle('active',button.dataset.composerMode===composerMode));applyMode(form);return}const easyTypeButton=event.target.closest('[data-easy-type]');if(easyTypeButton){easyType=easyTypeButton.dataset.easyType;easyPhrases=[];if(easyType!=='flight')flightTravelDraft=null;commitRaw(form,buildRaw(easyType,easySubject,easyPhrases));easyPanel(form);return}const easyOption=event.target.closest('[data-easy-option]');if(easyOption){const item=easyOption.dataset.easyOption;easyPhrases=easyPhrases.includes(item)?easyPhrases.filter((v)=>v!==item):[...easyPhrases,item];commitRaw(form,buildRaw(easyType,easySubject,easyPhrases));easyPanel(form);return}const builderTypeButton=event.target.closest('[data-builder-type]');if(builderTypeButton){builderType=builderTypeButton.dataset.builderType;builderPhrases=[];builderGroup='basic';builderAttribute='';if(builderType!=='flight')flightTravelDraft=null;commitRaw(form,buildRaw(builderType,builderSubject,builderPhrases));builderPanel(form);return}const attr=event.target.closest('[data-builder-attribute]');if(attr){builderGroup=attr.dataset.builderGroup||'basic';builderAttribute=attr.dataset.builderAttribute;builderPanel(form);return}const builderOption=event.target.closest('[data-builder-option]');if(builderOption){const item=builderOption.dataset.builderOption;builderPhrases=builderPhrases.includes(item)?builderPhrases.filter((v)=>v!==item):[...builderPhrases,item];commitRaw(form,buildRaw(builderType,builderSubject,builderPhrases));builderPanel(form)}});
form.addEventListener('input',(event)=>{if(event.target.id==='easy-subject'){easySubject=event.target.value;commitRaw(form,buildRaw(easyType,easySubject,easyPhrases));easyPanel(form)}if(event.target.id==='builder-subject'){builderSubject=event.target.value;commitRaw(form,buildRaw(builderType,builderSubject,builderPhrases));builderPanel(form)}if(event.target.id==='query'&&composerMode==='text'){syncFlightDraftFromRaw(event.target.value,form);textPanel(form)}});form.querySelectorAll('[data-composer-mode]').forEach((button)=>button.classList.toggle('active',button.dataset.composerMode===composerMode));applyMode(form)}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function scan(){const form=document.querySelector('#watch-form');if(form)enhance(form)}
new MutationObserver(scan).observe(document.querySelector('#app'),{childList:true,subtree:true});scan();
