name: lockgen-temporary

on:
  push:
    branches:
      - feat/release-audit-hardening

jobs:
  lockgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
      - name: Generate lockfile
        run: npm install --package-lock-only --ignore-scripts --no-audit --no-fund
      - name: Print lockfile
        run: |
          echo LOCKFILE_BASE64_BEGIN
          base64 -w0 package-lock.json
          echo
          echo LOCKFILE_BASE64_END
